### ISSUE TITLE
Tuned CPU isolation not applied

### ISSUE THREAD

**Issue by ric79** [redhat-performance/tuned#98]
I'm trying to configure cpu-partitioning on RHEL7 or CENTOS7.2 but the result is always void..

```
$ yum install -y tuned-profiles-cpu-partitioning-2.8.0-5.el7
$ more /proc/cpuinfo | grep processor | wc -l
56

$ more /etc/tuned/cpu-partitioning-variables.conf
isolated_cores=4-13,16-27,32-41,44-55

$ tuned-adm profile cpu-partitioning
$ tuned-adm active
  Current active profile: cpu-partitioning

$ reboot
$ more /sys/devices/system/cpu/isolated
[ ... void line ...]

```

Rr

Here there is the activation log:

```
2018-04-30 13:11:37,939 INFO     tuned.plugins.plugin_systemd: setting 'CPUAffinity' to '0 1 2 3 14 15 28 29 30 31 42 43' in the '/etc/systemd/system.conf'
2018-04-30 13:11:37,939 INFO     tuned.plugins.plugin_script: calling script '/usr/lib/tuned/cpu-partitioning/script.sh' with arguments '['start']'
2018-04-30 13:11:38,276 INFO     tuned.plugins.plugin_bootloader: installing additional boot command line parameters to grub2
2018-04-30 13:11:38,277 INFO     tuned.plugins.plugin_bootloader: generating initrd image from directory '/tmp/tmp.B7pQWne8tY'
2018-04-30 13:11:38,286 INFO     tuned.plugins.plugin_bootloader: installing initrd image as '/boot/tuned-initrd.img'
2018-04-30 13:11:38,287 INFO     tuned.plugins.plugin_bootloader: removing directory '/tmp/tmp.B7pQWne8tY'
2018-04-30 13:11:38,288 INFO     tuned.daemon.daemon: static tuning from profile 'cpu-partitioning' applied
2018-04-30 13:11:58,231 INFO     tuned.daemon.daemon: verifying profile(s): cpu-partitioning
performance unix
```

**Comment by yarda** [comment]
It uses CPUAffinity, not isolcpus, so you will not see it in /sys/devices/system/cpu/isolated:
https://bugzilla.redhat.com/show_bug.cgi?id=1359956

If you need isolcpus, try e.g realtime profile.

**Comment by ric79** [comment]
Ops... thanks. But how I can verify CPUAffinity after reboot?

**Comment by yarda** [comment]
With systemd CPUAffinity the idea is that the 'init' process takes the configured affinity and all other processes (childs of init) will inherit it (if not overridden per process).

You can check the systemd setting after reboot by hand or by running:
# tuned-adm verify
Or you can use tool like 'tuna', e.g.:
$ tuna -g
and check the affinity of the init process (PID 1) and all other running processes.

**Comment by ric79** [comment]
Thanks,
something on my system in still wrong:

> $ tuned-adm verify
> Verification failed, current system settings differ from the preset profile.
> 
> $ more /var/log/tuned/tuned.log
> 2018-04-30 17:19:43,825 ERROR    tuned.plugins.base: verify: failed: '/sys/devices/virtual/workqueue/cpumask' = '000c00,f000c00f', expected '00000c00,f000c00f'
> 2018-04-30 17:19:43,826 ERROR    tuned.plugins.base: verify: failed: '/sys/bus/workqueue/devices/writeback/cpumask' = '000c00,f000c00f', expected '00000c00,f000c00f'
> 2018-04-30 17:19:43,826 INFO     tuned.plugins.base: verify: passed: 'cpu_affinity' = '0 1 2 3 14 15 28 29 30 31 42 43'
> 2018-04-30 17:19:43,826 INFO     tuned.plugins.plugin_script: calling script '/usr/lib/tuned/cpu-partitioning/script.sh' with arguments '['verify']'
> 2018-04-30 17:19:43,890 ERROR    tuned.plugins.plugin_script: script '/usr/lib/tuned/cpu-partitioning/script.sh' error: 1, 'verify: failed: irqaffinity (/proc/irq/340/smp_affinity) inplacemask=80
> 0 shouldbemask=c00f000c00f'
> 2018-04-30 17:19:43,890 ERROR    tuned.plugins.plugin_script: verify: failed: '['/usr/lib/tuned/cpu-partitioning/script.sh']'
> 2018-04-30 17:19:43,891 ERROR    tuned.plugins.plugin_bootloader: verify: failed: 'cmdline' = 'set(['intel_pstate=disable', 'nohz=on', 'nosoftlockup'])', expected 'set(['nohz_full=4-13,16-27,32-4
> 1,44-55', 'nosoftlockup', 'nohz=on', 'rcu_nocbs=4-13,16-27,32-41,44-55', 'intel_pstate=disable', 'tuned.non_isolcpus=00000c00,f000c00f'])'
>

**Comment by yarda** [comment]
Is it after reboot? E.g.: the last line says there is no nohz_full on the kernel command line, i.e. probably not rebooted.

**Comment by ric79** [comment]
Yes this is after reboot.
Maybe I neet to chang the grub config

```
more /etc/default/grub
  GRUB_TIMEOUT=5
  GRUB_DISTRIBUTOR="$(sed 's, release .*$,,g' /etc/system-release)"
  GRUB_DEFAULT=saved
  GRUB_DISABLE_SUBMENU=true
  GRUB_TERMINAL_OUTPUT="console"
  GRUB_CMDLINE_LINUX="console=tty0 console=ttyS0,115200n8 crashkernel=auto rhgb quiet default_hugepagesz=1G hugepagesz=1G hugepages=170 hugepagesz=2M hugepages=2048"
  GRUB_DISABLE_RECOVERY="true"
 GRUB_CMDLINE_LINUX_DEFAULT="${GRUB_CMDLINE_LINUX_DEFAULT:+$GRUB_CMDLINE_LINUX_DEFAULT }\$tuned_params"
  GRUB_INITRD_OVERLAY="${GRUB_INITRD_OVERLAY:+$GRUB_INITRD_OVERLAY }\$tuned_initrd"
```

**Comment by yarda** [comment]
Hmm, your /proc/cmdline doesn't correspond with the previous snip from the tuned.log. Did you change the CPU list in between?

Also check:
```# tuned-adm active```
Whether the correct profile is activated, then check /etc/tuned/bootcmdline, whether the settings there corresponds with your /proc/cmdline. If not, try to regenerate you grub config by:
```# grub2-mkconfig -o PATH_TO_YOUR_GRUB.CFG```
and reboot.

**Comment by olysonek** [comment]
> 2018-04-30 17:19:43,825 ERROR    tuned.plugins.base: verify: failed: '/sys/devices/virtual/workqueue/cpumask' = '000c00,f000c00f', expected '00000c00,f000c00f'
> 2018-04-30 17:19:43,826 ERROR    tuned.plugins.base: verify: failed: '/sys/bus/workqueue/devices/writeback/cpumask' = '000c00,f000c00f', expected '00000c00,f000c00f'

Notice that the values differ only in the leading zeros. They don't actually differ. These errors should be fixed by https://github.com/redhat-performance/tuned/pull/99

**Comment by ric79** [comment]
Thanks! I modified Grub and rebooted. Now the test is still not passed but I think it is just caused by the bug on leading zeros. 

```
2018-05-03 11:19:38,077 ERROR    tuned.plugins.base: verify: failed: '/sys/devices/virtual/workqueue/cpumask' = '000c00,f000c00f', expected '00000c00,f000c00f'
2018-05-03 11:19:38,078 ERROR    tuned.plugins.base: verify: failed: '/sys/bus/workqueue/devices/writeback/cpumask' = '000c00,f000c00f', expected '00000c00,f000c00f'
2018-05-03 11:19:38,078 INFO     tuned.plugins.base: verify: passed: 'cpu_affinity' = '0 1 2 3 14 15 28 29 30 31 42 43'
2018-05-03 11:19:38,078 INFO     tuned.plugins.plugin_script: calling script '/usr/lib/tuned/cpu-partitioning/script.sh' with arguments '['verify']'
2018-05-03 11:19:38,124 ERROR    tuned.plugins.plugin_script: script '/usr/lib/tuned/cpu-partitioning/script.sh' error: 1, 'verify: failed: irqaffinity (/proc/irq/18/smp_affinity) inplacemask=fff
3ffffff3fff shouldbemask=c00f000c00f'
2018-05-03 11:19:38,124 ERROR    tuned.plugins.plugin_script: verify: failed: '['/usr/lib/tuned/cpu-partitioning/script.sh']'
2018-05-03 11:19:38,125 INFO     tuned.plugins.plugin_bootloader: verify: passed: 'cmdline' = 'set(['nohz_full=4-13,16-27,32-41,44-55', 'nosoftlockup', 'nohz=on', 'rcu_nocbs=4-13,16-27,32-41,44-5
5', 'intel_pstate=disable', 'tuned.non_isolcpus=00000c00,f000c00f'])'

```

**Comment by yarda** [comment]
You are probably affected by bug:
https://bugzilla.redhat.com/show_bug.cgi?id=1528368

It should be already fixed upstream by c2eb0858d140d67c79b7b78043f1c833f0de0832.
You can rebuilt the Tuned package yourself or just apply the patch over the installed Tuned (it's not clean way, but it should work).

**Comment by olysonek** [comment]
All issues should be resolved now, closing.
